version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_resources
    ports:
      - '5330:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local