version: "3.2"

services:
  app:
    image: "library-service"
    build:
      context: .
    container_name: library-service
    depends_on:
     - postgresqldb
    ports:
     - 8030:8030
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/postgres
     - SPRING_DATASOURCE_USERNAME=postgres
     - SPRING_DATASOURCE_PASSWORD=postgres
     - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresqldb:
    image: 'postgres:13.1-alpine'
    container_name: postgresqldb
    ports:
      - 5330:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres