insert into category (category_name)
values ('Fantasy'),
       ('Adventure'),
       ('Romance'),
       ('Contemporary'),
       ('Dystopian'),
       ('Mystery'),
       ('Horror'),
       ('Thriller'),
       ('Paranormal'),
       ('Science Fiction'),
       ('Children’s'),
       ('Memoir'),
       ('Cookbook'),
       ('Art'),
       ('Self-help'),
       ('Development'),
       ('Motivational'),
       ('Health'),
       ('History'),
       ('Travel'),
       ('Guide / How-to'),
       ('Families & Relationships'),
       ('Humor');