INSERT INTO public.publisher (publisher_name) VALUES
	 ('Simonis, Wolff and Haag'),
	 ('Cassin, Hayes and Gorczany'),
	 ('Hammes, Effertz and Goodwin'),
	 ('Paucek Inc'),
	 ('Bashirian LLC'),
	 ('Sawayn, Fahey and Wiegand'),
	 ('Metz, Wolff and Hartmann'),
	 ('Kshlerin-Bins'),
	 ('Lubowitz-Paucek'),
	 ('Ryan LLC');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Durgan, Treutel and Hegmann'),
	 ('Kassulke LLC'),
	 ('Schinner-Klein'),
	 ('Waters, MacGyver and McClure'),
	 ('Shields, Rutherford and Jaskolski'),
	 ('Johnson, Bayer and Hintz'),
	 ('Hegmann Inc'),
	 ('Ondricka, Gerlach and Schuster'),
	 ('King LLC'),
	 ('Runte, Balistreri and Hartmann');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Johnson-Dicki'),
	 ('Reichert-Maggio'),
	 ('Quitzon-Wiegand'),
	 ('Reynolds Group'),
	 ('Barton, McCullough and Bartell'),
	 ('Metz and Sons'),
	 ('Muller, White and Legros'),
	 ('Stark LLC'),
	 ('Kuhic Group'),
	 ('Rippin Group');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Tremblay, Hoppe and Green'),
	 ('Rippin Group'),
	 ('Orn and Sons'),
	 ('Gislason and Sons'),
	 ('Ratke and Sons'),
	 ('Quitzon-Spencer'),
	 ('Crist-Kub'),
	 ('Romaguera Inc'),
	 ('Corkery, Harvey and Smith'),
	 ('Runolfsson, Schimmel and Sporer');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Langosh-Homenick'),
	 ('Sauer, Blanda and Krajcik'),
	 ('Runolfsdottir, Cormier and Kunze'),
	 ('O''Connell, Jerde and Huel'),
	 ('Ryan-Wyman'),
	 ('Marquardt-Willms'),
	 ('Hahn-Lubowitz'),
	 ('Bednar, Kuphal and Glover'),
	 ('Bradtke-Kuhn'),
	 ('Kerluke Inc');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Skiles, Boehm and Lindgren'),
	 ('Schuster Inc'),
	 ('Zemlak-Bednar'),
	 ('Bernier, Auer and Barton'),
	 ('Kessler-D''Amore'),
	 ('Berge-Bednar'),
	 ('Jacobi, Leffler and Douglas'),
	 ('Abbott-Windler'),
	 ('Murazik, Kunde and Kihn'),
	 ('Batz-Farrell');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Renner-Kuphal'),
	 ('Moore and Sons'),
	 ('Zulauf-Dare'),
	 ('Stiedemann, Collins and Grimes'),
	 ('Dicki, Jaskolski and Stiedemann'),
	 ('Hand Inc'),
	 ('Borer-Watsica'),
	 ('Veum, Kutch and Beahan'),
	 ('Kessler LLC'),
	 ('Little, Lebsack and Dietrich');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Ankunding-Beer'),
	 ('Turner-Orn'),
	 ('Sanford, Gutmann and Hyatt'),
	 ('Shields, Beer and Pacocha'),
	 ('Nolan, Hintz and Feil'),
	 ('Volkman, Smitham and Schaefer'),
	 ('Kirlin and Sons'),
	 ('Harris, Hettinger and Ryan'),
	 ('Ryan, Ledner and Murazik'),
	 ('Blick-Volkman');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Rau Group'),
	 ('Lindgren-Johns'),
	 ('Mayert-O''Keefe'),
	 ('Cummings Group'),
	 ('Cormier, Bahringer and Runolfsson'),
	 ('Carroll, Crist and Dicki'),
	 ('Reinger-Legros'),
	 ('Fadel-Langworth'),
	 ('Satterfield Group'),
	 ('Windler-Dooley');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Baumbach-Friesen'),
	 ('Osinski, Balistreri and Wiza'),
	 ('Thiel-West'),
	 ('Mertz, Kuhn and Murphy'),
	 ('Runolfsson Group'),
	 ('Breitenberg-King'),
	 ('Kshlerin-Kautzer'),
	 ('D''Amore Inc'),
	 ('Breitenberg, Volkman and Corwin'),
	 ('Bednar-Lakin');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('DuBuque, Wisoky and Oberbrunner'),
	 ('Ziemann-Walsh'),
	 ('Zemlak LLC'),
	 ('Wiza Inc'),
	 ('Ratke Group'),
	 ('Powlowski, Rodriguez and Hackett'),
	 ('Oberbrunner-Stroman'),
	 ('Jenkins, Murphy and Jerde'),
	 ('Lebsack-McGlynn'),
	 ('Larkin, McGlynn and Ruecker');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Pacocha, Kris and Weimann'),
	 ('Feeney, Huel and Berge'),
	 ('Mayert-Windler'),
	 ('Feil LLC'),
	 ('Yundt-Strosin'),
	 ('Deckow, Brekke and Stiedemann'),
	 ('Bednar, Johns and Miller'),
	 ('Jones-Kautzer'),
	 ('Rowe Inc'),
	 ('Krajcik, Kerluke and Mosciski');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Gorczany-Bailey'),
	 ('Gottlieb Inc'),
	 ('Kutch Group'),
	 ('Hermiston, Kovacek and Feil'),
	 ('Miller, Nolan and Konopelski'),
	 ('Little Inc'),
	 ('Price Inc'),
	 ('Kunze-Dooley'),
	 ('Friesen, Mertz and Moore'),
	 ('Bogisich, Mosciski and Lind');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Gorczany and Sons'),
	 ('Will-Gibson'),
	 ('Volkman-Hauck'),
	 ('Streich and Sons'),
	 ('Boyle, Hermiston and Keeling'),
	 ('Luettgen Group'),
	 ('Maggio-Jones'),
	 ('Davis, Boehm and Bode'),
	 ('Ruecker and Sons'),
	 ('Sporer-Conroy');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Konopelski Group'),
	 ('Lynch-Morissette'),
	 ('Stoltenberg, Ruecker and O''Conner'),
	 ('Baumbach Inc'),
	 ('Hickle, Nolan and Haley'),
	 ('Kilback-Shanahan'),
	 ('Hane-Powlowski'),
	 ('Kovacek Group'),
	 ('Reynolds, Huel and Marvin'),
	 ('Hane-Kassulke');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Yundt-McClure'),
	 ('Zieme, Lockman and Collins'),
	 ('Dickens Group'),
	 ('Maggio-Bahringer'),
	 ('Brown-Bayer'),
	 ('Klocko LLC'),
	 ('Leannon and Sons'),
	 ('Ryan-Moore'),
	 ('Hauck Inc'),
	 ('Parker-Jaskolski');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Weissnat-Prosacco'),
	 ('Huel, Klein and Wiegand'),
	 ('Douglas, O''Conner and Mertz'),
	 ('Lebsack-Boyer'),
	 ('Maggio Inc'),
	 ('Romaguera, Champlin and Stanton'),
	 ('Gottlieb LLC'),
	 ('Kemmer, Bashirian and Watsica'),
	 ('Hilll and Sons'),
	 ('Franecki-Hermiston');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Stamm-Casper'),
	 ('Predovic-Streich'),
	 ('VonRueden-Kris'),
	 ('Will, Bernhard and Breitenberg'),
	 ('Ortiz, Windler and Kuphal'),
	 ('Mosciski Group'),
	 ('Runolfsdottir Group'),
	 ('Tromp-Feil'),
	 ('Lind Inc'),
	 ('Effertz, Kihn and Bashirian');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Bashirian Inc'),
	 ('Hermann Group'),
	 ('Daugherty-Cremin'),
	 ('Nolan-Pfeffer'),
	 ('Strosin and Sons'),
	 ('Padberg, Jones and Kirlin'),
	 ('Kassulke-Maggio'),
	 ('Little, Nolan and Koss'),
	 ('Stokes and Sons'),
	 ('Bode, O''Kon and Schulist');
INSERT INTO public.publisher (publisher_name) VALUES
	 ('Emard LLC'),
	 ('Fay-Graham'),
	 ('Dicki Group'),
	 ('Streich-Pacocha'),
	 ('Deckow, Robel and Greenholt'),
	 ('Blick-Hansen'),
	 ('Gutmann, Nolan and Brakus'),
	 ('Schmidt, McDermott and Shields'),
	 ('Schulist-Gaylord'),
	 ('Rau Group');
