INSERT INTO public.author (last_name,first_name) VALUES
	 ('Marquot','Verina'),
	 ('Yeardsley','Cristie'),
	 ('Stanbro','Bobbette'),
	 ('Coutts','Allie'),
	 ('Brithman','Yetty'),
	 ('Wigginton','Perice'),
	 ('Purple','Jarrett'),
	 ('McMeekan','Rosette'),
	 ('Fuchs','Adelle'),
	 ('Postlethwaite','Alexandre');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Iannini','Hersch'),
	 ('Choke','Lettie'),
	 ('Olivier','Faye'),
	 ('Wedlake','Bengt'),
	 ('Bosdet','Annalee'),
	 ('Killen','Halie'),
	 ('Meni','Sigismundo'),
	 ('Wearne','Jobi'),
	 ('Harbison','Coriss'),
	 ('Farney','Rafi');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Matveichev','Stesha'),
	 ('Saltman','Levy'),
	 ('Streets','Ardith'),
	 ('Kiwitz','Cassie'),
	 ('Jain','Bernardina'),
	 ('Stainsby','Phyllida'),
	 ('McGinly','Babb'),
	 ('Union','Candide'),
	 ('Bittlestone','Gae'),
	 ('Bedrosian','Read');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Brunstan','Mathilda'),
	 ('Bielfeldt','Filia'),
	 ('Whitmarsh','Kristopher'),
	 ('Vinson','Ashlan'),
	 ('Tivers','Jerrilyn'),
	 ('Prozillo','Rivi'),
	 ('Cousen','Haroun'),
	 ('Heffron','Hesther'),
	 ('Waters','Winni'),
	 ('Chainey','Conway');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Scantlebury','Steffane'),
	 ('Gabala','Terrel'),
	 ('Bolliver','Bridgette'),
	 ('Povey','Layton'),
	 ('Mushett','Bordy'),
	 ('Zimmer','Garnette'),
	 ('Ricardot','Sander'),
	 ('Filde','Valeria'),
	 ('Cheves','Elihu'),
	 ('Biasini','Ealasaid');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Raubheim','Dinny'),
	 ('Guile','Phillie'),
	 ('MacGaffey','Dermot'),
	 ('Dibley','Rora'),
	 ('Jahncke','Suellen'),
	 ('McDowell','Dru'),
	 ('Coslett','Wynnie'),
	 ('Guitte','Sianna'),
	 ('Keeting','Lark'),
	 ('Burree','Noe');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Ramsdale','Ibrahim'),
	 ('Littler','Billie'),
	 ('Dunn','Jasmine'),
	 ('Gourlay','Fredrika'),
	 ('Ickovitz','Miguel'),
	 ('Andrzejak','Judd'),
	 ('McHale','Astrix'),
	 ('Coucher','Marilyn'),
	 ('Blackmuir','Terri'),
	 ('Manjin','Genna');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Louche','Danell'),
	 ('Peach','Beverie'),
	 ('Zannuto','Othilie'),
	 ('Fallon','Anne'),
	 ('Anmore','Rhys'),
	 ('Phillis','Ysabel'),
	 ('Fraulo','Farrah'),
	 ('Dobby','Torr'),
	 ('Spollen','Sioux'),
	 ('Digges','Nanny');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Berrycloth','Kyla'),
	 ('Hebard','Anne'),
	 ('Rowledge','Arleta'),
	 ('Maffiotti','Loleta'),
	 ('Sparry','Florencia'),
	 ('Briiginshaw','Cherida'),
	 ('Gres','Nikolia'),
	 ('MacFaul','Phillipe'),
	 ('Darkott','Ade'),
	 ('McConachie','Haley');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Rodear','Hillery'),
	 ('Sancias','Powell'),
	 ('Shelford','Anya'),
	 ('Neely','Tyne'),
	 ('Balchin','Corina'),
	 ('Mottershaw','Dora'),
	 ('Standley','Jinny'),
	 ('Alderton','Killy'),
	 ('Demead','Xylina'),
	 ('MacNaughton','Neilla');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Arnecke','Anjela'),
	 ('Alexandrescu','Lisle'),
	 ('Tees','Jacintha'),
	 ('Ciccarelli','Demott'),
	 ('Everly','Gilbert'),
	 ('Coopland','Bunny'),
	 ('Heape','Britt'),
	 ('Sinnatt','Rebbecca'),
	 ('Blamire','Demetrius'),
	 ('Morrad','Grenville');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Van Schafflaer','Tomas'),
	 ('Tadlow','Camel'),
	 ('Glas','Urbanus'),
	 ('Chiechio','Mitchel'),
	 ('Hazlewood','Jeffrey'),
	 ('Gley','Jehu'),
	 ('Dey','Winny'),
	 ('Killford','Nigel'),
	 ('Gally','Ester'),
	 ('Morbey','Joane');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Tembridge','Morgan'),
	 ('Salisbury','Franky'),
	 ('Dripp','Michelina'),
	 ('Sorsby','Norene'),
	 ('Corroyer','Finlay'),
	 ('Snell','Amalee'),
	 ('Winchcomb','Bobbie'),
	 ('Dudenie','Ethel'),
	 ('Tozer','Ric'),
	 ('Melliard','Tove');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('O''Crigane','Reinaldos'),
	 ('Feye','Michel'),
	 ('Bunford','Jordana'),
	 ('Doggrell','Felipe'),
	 ('Armor','Brande'),
	 ('Dishman','Ginevra'),
	 ('Bullerwell','Roda'),
	 ('Flaubert','Nevile'),
	 ('Higgonet','Roxine'),
	 ('Matfin','Neille');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Alesio','Barnett'),
	 ('MacMenamy','Esmeralda'),
	 ('Wallington','Kanya'),
	 ('Jump','Sigismondo'),
	 ('Kingsman','Anett'),
	 ('Hasnip','Sonny'),
	 ('Perris','Delainey'),
	 ('Spohr','Aylmar'),
	 ('Smithson','Laraine'),
	 ('Yarwood','Revkah');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Roarty','Priscilla'),
	 ('Colbran','Althea'),
	 ('Steabler','Antonia'),
	 ('Laming','Page'),
	 ('Slyford','Janice'),
	 ('Maliphant','Gil'),
	 ('Samsin','Valdemar'),
	 ('Rable','Megen'),
	 ('Duggen','Carie'),
	 ('Shillitoe','Harlie');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Kenrick','Faith'),
	 ('De La Haye','Tommie'),
	 ('Gartin','Mile'),
	 ('Clemitt','Ilysa'),
	 ('Tither','Egor'),
	 ('Malkin','Wilden'),
	 ('Deboick','Erna'),
	 ('Novis','Morna'),
	 ('Tysall','Charity'),
	 ('Medley','Pietrek');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Scotti','Allx'),
	 ('MacPhail','Fonz'),
	 ('Ferfulle','Prescott'),
	 ('Ahmed','Ines'),
	 ('Planke','Lauren'),
	 ('Southcomb','Yorgos'),
	 ('Jakoubec','Fair'),
	 ('Tomadoni','Winn'),
	 ('Wycherley','Pierette'),
	 ('McGray','Chancey');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('McCambridge','Jillene'),
	 ('MacCardle','Lila'),
	 ('Berzin','Gradeigh'),
	 ('Mangenet','Tobias'),
	 ('Vinck','Olwen'),
	 ('Lyndon','Levy'),
	 ('Barribal','Edvard'),
	 ('McMakin','Iggy'),
	 ('Hiley','Malinde'),
	 ('Hurdis','Raddie');
INSERT INTO public.author (last_name,first_name) VALUES
	 ('Sondon','Bernice'),
	 ('Spry','Camilla'),
	 ('Boarer','Jada'),
	 ('Janicki','Harlan'),
	 ('Bosence','Dodi'),
	 ('Lethabridge','Natalie'),
	 ('Symper','Marrissa'),
	 ('Melmore','Werner'),
	 ('Karus','Addy'),
	 ('Broddle','Barney');
